# Generated by Django 3.2.8 on 2021-10-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(db_index=True)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp.partofspeech')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp.text')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
